from django.conf.urls import url, include
from django.conf.urls.static import static
from django.http import HttpResponse
from . import views
from zt import settings

urlpatterns = [
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', views.main, name='main'),
    # url(r'^login/$', views.log_in, name='login'),
    url(r'^login/(?P<next_url>.*)/$', views.log_in, name='login'),
    # url(r'^registration/$', views.registration, name='registration'),
    url(r'^registration/(?P<next_url>.*)/$', views.registration, name='registration'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^catalog/(?P<category_path>(?:[-\w]+/)+)$', views.catalog_category, name='catalog_category'),
    url(r'^comments/', include('django_comments.urls')),
    # url(r'^product/comments/', include('django_comments.urls')),
    url(r'^products_search/$', views.products_search, name='products_search'),
    url(r'^prajjsy/$', views.prajjsy, name='prajjsy'),
    # url(r'^articles/comments/', include('django_comments.urls')),
    url(r'^articles/$', views.articles, name='articles'),
    url(r'^articles/page-(?P<page_number>[0-9]+)/$', views.articles, name='articles_page'),
    url(r'^articles/(?P<article_slug>[-\w]+)/$', views.articles_detail, name='articles_detail'),
    url(r'^articles/tag/(?P<tag_in_url>[^/]+)/$', views.articles, name='articles_tag'),
    url(r'^articles/tag/(?P<tag_in_url>[^/]+)/page-(?P<page_number>[0-9]+)/$', views.articles,
        name='articles_tag_page'),
    # url(r'^news/comments/', include('django_comments.urls')),
    url(r'^news/$', views.news, name='news'),
    url(r'^news/archive/$', views.news_archive, name='news_archive'),
    url(r'^news/archive/page-(?P<page_number>[0-9]+)/$', views.news_archive, name='news_archive_page'),
    url(r'^news/page-(?P<page_number>[0-9]+)/$', views.news_archive, name='news_page'),
    url(r'^news/(?P<news_slug>[-\w]+)/$', views.news_detail, name='news_detail'),
    url(r'^news/tag/(?P<tag_in_url>[^/]+)/$', views.news_archive, name='news_tag'),
    url(r'^news/tag/(?P<tag_in_url>[^/]+)/page-(?P<page_number>[0-9]+)/$', views.news_archive,
        name='news_tag_page'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^dostavka/$', views.dostavka, name='dostavka'),
    url(r'^dostavka/mezhdunarodnaja-dostavka/$', views.mezhdunarodnaja_dostavka, name='mezhdunarodnaja_dostavka'),
    url(r'^geografija-prodazh/$', views.geografija_prodazh, name='geografija_prodazh'),
    url(r'^dokumentatsija/$', views.dokumentatsija, name='dokumentatsija'),
    url(r'^dokumentatsija/razreshenie-na-primenenie/$', views.razreshenie_na_primenenie,
        name='razreshenie_na_primenenie'),
    url(r'^dokumentatsija/sertifikaty/$', views.sertifikaty, name='sertifikaty'),
    url(r'^dokumentatsija/tekhnicheskaja-dokumentatsija/$', views.tekhnicheskaja_dokumentatsija,
        name='tekhnicheskaja_dokumentatsija'),
    url(r'^dokumentatsija/zachem-nuzhna-dokumentatsija/$', views.zachem_nuzhna_dokumentatsija,
        name='zachem_nuzhna_dokumentatsija'),
    url(r'^dokumentatsija/tovarnye-znaki/$', views.tovarnye_znaki, name='tovarnye_znaki'),
    url(r'^dokumentatsija/tovarnye-znaki/mezhdunarodnye-tovarnye-znaki/$', views.mezhdunarodnye_tovarnye_znaki,
        name='mezhdunarodnye_tovarnye_znaki'),
    url(r'^dokumentatsija/tovarnye-znaki/tovarnyjj-znak-zachem-on/$', views.tovarnyjj_znak_zachem_on,
        name='tovarnyjj_znak_zachem_on'),
    url(r'^photogallery/$', views.photogallery, name='photogallery'),
    url(r'^photogallery/page-(?P<page_number>[0-9]+)/$$', views.photogallery, name='photogallery'),
    url(r'^videogallery/$', views.videogallery, name='videogallery'),
    url(r'^videogallery/page-(?P<page_number>[0-9]+)/$$', views.videogallery, name='videogallery'),
    url(r'^videootzyvy/$', views.videootzyvy, name='videootzyvy'),
    url(r'^videootzyvy/page-(?P<page_number>[0-9]+)/$$', views.videootzyvy, name='videootzyvy'),
    url(r'^photogallery/(?P<photogallery_slug>[-\w]+)/$', views.photogallery_detail_page, name='photogallery_detail'),
    url(r'^photogallery/(?P<photogallery_slug>[-\w]+)/page-(?P<page_number>[0-9]+)/$', views.photogallery_detail_page, name='photogallery_detail_page'),
    url(r'^o-kompanii/$', views.about, name='about'),
    url(r'^o-kompanii/otzyvy/$', views.otzyvy, name='otzyvy'),
    url(r'^o-kompanii/employee/$', views.employee, name='employee'),
    url(r'^o-kompanii/employee/info/(?P<employee_name>[-\w]+)$', views.employee_info, name='employee_info'),
    url(r'^o-kompanii/chasto-zadavaemye-voprosy-faq/$', views.faq, name='faq'),
    url(r'^o-kompanii/partnery/$', views.partnery, name='partnery'),
    url(r'^o-kompanii/vacancy/$', views.vacancy, name='vacancy'),
    url(r'^o-kompanii/nagrady/$', views.nagrady, name='nagrady'),
    url(r'^proizvodstvo-zavoda-triumf/$', views.proizvodstvo_zavoda_triumf, name='proizvodstvo_zavoda_triumf'),
    url(r'^prajjsy/gibkaja-sistema-skidok/$', views.gibkaja_sistema_skidok, name='gibkaja_sistema_skidok'),
    url(r'^callme_form_process/(?P<next_url>.*)/$', views.callme_form_process, name='callme_form_process'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^robots.txt$',
        lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
