from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^catalog/$', views.catalog, name='catalog'),
    url(r'^catalog/[-\w]+/$', views.catalog_category, name='catalog_category'),
    url(r'^catalog/[-\w]+/[-\w]+/$', views.product_or_products, name='product_or_products'),
    url(r'^catalog/[-\w]+/[-\w]+/[-\w]+/$', views.product_or_products, name='product_or_products'),
    url(r'^prajjsy/$', views.prajjsy, name='prajjsy'),
    url(r'^articles/$', views.articles, name='articles'),
    url(r'^articles/[-\w]+/$', views.articles_detail, name='articles_detail'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^dostavka/$', views.dostavka, name='dostavka'),
    url(r'^dostavka/mezhdunarodnaja-dostavka/$', views.mezhdunarodnaja_dostavka, name='mezhdunarodnaja_dostavka'),
    url(r'^geografija-prodazh/$', views.geografija_prodazh, name='geografija_prodazh'),
    url(r'^dokumentatsija/$', views.dokumentatsija, name='dokumentatsija'),
    url(r'^dokumentatsija/razreshenie-na-primenenie/$', views.razreshenie_na_primenenie,
        name='razreshenie_na_primenenie'),
    url(r'^dokumentatsija/sertifikaty/$', views.sertifikaty, name='sertifikaty'),
    url(r'^dokumentatsija/tekhnicheskaja-dokumentatsija/$', views.tekhnicheskaja_dokumentatsija,
        name='tekhnicheskaja_dokumentatsija'),
    url(r'^dokumentatsija/zachem-nuzhna-dokumentatsija/$', views.zachem_nuzhna_dokumentatsija,
        name='zachem_nuzhna_dokumentatsija'),
    url(r'^dokumentatsija/tovarnye-znaki/$', views.tovarnye_znaki, name='tovarnye_znaki'),
    url(r'^dokumentatsija/tovarnye-znaki/mezhdunarodnye-tovarnye-znaki/$', views.mezhdunarodnye_tovarnye_znaki,
        name='mezhdunarodnye_tovarnye_znaki'),
    url(r'^dokumentatsija/tovarnye-znaki/tovarnyjj-znak-zachem-on/$', views.tovarnyjj_znak_zachem_on,
        name='tovarnyjj_znak_zachem_on'),
]
