# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 08:17
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('preview_post', models.TextField(max_length=200)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
                ('author', models.TextField(default=b'', max_length=200)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('title', models.CharField(default=b'', max_length=100)),
                ('text', models.TextField(default=b'')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u0432',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_content', models.FileField(blank=True, null=True, upload_to=b'media/files/')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('type', models.CharField(default=b'', max_length=100)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('text', models.TextField()),
                ('title', models.CharField(default=b'', max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f',
                'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0435\u0438',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to=b'media/gallery/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Gallery')),
            ],
            options={
                'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432 \u0433\u0430\u043b\u0435\u0440\u0435\u0435',
                'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0432 \u0433\u0430\u043b\u0435\u0440\u0435\u0435',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'images/')),
            ],
            options={
                'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('preview_post', models.TextField(max_length=200)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
                ('images', models.ManyToManyField(blank=True, default=None, null=True, related_name='news', to='zavod.Image')),
            ],
            options={
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('product_text', models.TextField()),
                ('title', models.CharField(default=b'', max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=b'')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct')),
                ('images', models.ManyToManyField(blank=True, default=None, null=True, related_name='products', to='zavod.Image')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0433',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='news', to='zavod.Tag'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='zavod.GalleryImage'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='categories', to='zavod.File'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='categories', to='zavod.Image'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct'),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='articles', to='zavod.Image'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='articles', to='zavod.Tag'),
        ),
    ]
