# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 05:31
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('preview_post', models.TextField(max_length=200)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.FileField(blank=True, null=True, upload_to=b'media/articles/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Article')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('parent_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u0432',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('product_text', models.TextField()),
                ('title', models.CharField(default=b'', max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=b'')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(blank=True, null=True, upload_to=b'media/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Product')),
            ],
        ),
    ]
