# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
