# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Article')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_content', models.FileField(blank=True, null=True, upload_to=b'media/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('type', models.CharField(default=b'', max_length=100)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('text', models.TextField()),
                ('title', models.CharField(default=b'', max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(blank=True, null=True, upload_to=b'media/gallery/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=b'', max_length=100, unique=True)),
                ('preview_post', models.TextField(max_length=200)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(default=b'', max_length=100)),
                ('seo_description', models.CharField(default=b'', max_length=100)),
                ('seo_keywords', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.FileField(blank=True, null=True, upload_to=b'media/news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.News')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.News')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='text',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='title',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zavod.Image'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Tag'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='zavod.GalleryImage'),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct'),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='category_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Image'),
        ),
        migrations.AddField(
            model_name='categoryfile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct'),
        ),
        migrations.AddField(
            model_name='categoryfile',
            name='category_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.File'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Tag'),
        ),
    ]
