# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_auto_20160826_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default=b'', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=b'', max_length=50, unique=True),
        ),
    ]
