# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_categoryproduct_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
