# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0005_auto_20160711_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('product_text', models.TextField()),
                ('seo_title', models.CharField(default='', max_length=100)),
                ('seo_description', models.CharField(default='', max_length=100)),
                ('seo_keywords', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_title',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.Product'),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct'),
        ),
    ]
