# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0007_auto_20160711_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
