# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0008_auto_20160711_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
