# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0010_auto_20160712_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='subproduct',
            options={'verbose_name': 'Вложенный продукт', 'verbose_name_plural': 'Вложенные продукты'},
        ),
    ]
