# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0011_auto_20160713_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zavod.CategoryProduct')),
            ],
            options={
                'verbose_name': 'Вложенная категория',
                'verbose_name_plural': 'Вложенные категории',
            },
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='SubProduct',
        ),
    ]
