# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0019_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
    ]
