# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0020_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
