# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0025_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
